---
label: services
hide_body: true
fields:
- name: section_title
  type: field_group
  config: {}
  fields:
  - name: it
    type: text
    config:
      required: false
    label: IT
  - name: en
    type: text
    config:
      required: false
    label: EN
  label: Section title
- name: services
  type: field_group_list
  fields:
  - name: it
    type: text
    config:
      required: false
    label: IT
  - name: en
    type: text
    config:
      required: false
    label: EN
  config:
    min: 
    max: 
    labelField: 
  label: Services
- name: image
  type: file
  config:
    maxSize: 64
  label: image
